# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MmUyMmE1YTE1MTBiNjUwNzBmNmFhZTVhMGI5ZDZlMzMyYzc2ZmJlMTdkOGQ5MzBhMWVlN2ZlZmE2NGRkOTczM2ExMjg2ZWI0ODliMjEzMTZmNDg0ZTRhOTgxZTYzNTkzZjhkMmQ1MzljN2FmY2Y0MzRhZTBiM2ZhZjZmYjExMjM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
